-- Authentication boundary and least-privilege RLS for CareerOS.
create or replace function public.is_portfolio_owner()
returns boolean
language sql
stable
security invoker
set search_path = ''
as $$
  select coalesce((auth.jwt() -> 'app_metadata' ->> 'portfolio_owner')::boolean, false);
$$;

revoke all on function public.is_portfolio_owner() from public;
grant execute on function public.is_portfolio_owner() to anon, authenticated;

create table if not exists public.site_content (
  page_key text primary key,
  content jsonb not null,
  updated_at timestamptz not null default now()
);
create table if not exists public.projects (
  id bigint generated by default as identity primary key,
  title text not null,
  description text not null,
  slug text unique,
  status text not null default 'pending' check (status in ('pending', 'approved', 'hidden')),
  visibility text not null default 'private' check (visibility in ('public', 'private')),
  owner_id uuid default auth.uid() references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

alter table public.projects add column if not exists status text not null default 'pending'
  check (status in ('pending', 'approved', 'hidden'));
alter table public.projects add column if not exists visibility text not null default 'private'
  check (visibility in ('public', 'private'));
alter table public.projects add column if not exists owner_id uuid default auth.uid()
  references auth.users(id) on delete set null;
create table if not exists public.skills (
  id bigint generated by default as identity primary key,
  name text not null,
  icon text,
  status text not null default 'pending' check (status in ('pending', 'approved', 'hidden')),
  visibility text not null default 'private' check (visibility in ('public', 'private')),
  owner_id uuid default auth.uid() references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);
alter table public.skills add column if not exists status text not null default 'pending'
  check (status in ('pending', 'approved', 'hidden'));
alter table public.skills add column if not exists visibility text not null default 'private'
  check (visibility in ('public', 'private'));
alter table public.skills add column if not exists owner_id uuid default auth.uid()
  references auth.users(id) on delete set null;
create table if not exists public.contacts (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(btrim(name)) between 1 and 100),
  email text not null check (char_length(email) between 3 and 254 and email ~* '^[^[:space:]@]+@[^[:space:]@]+\.[^[:space:]@]+$'),
  message text not null check (char_length(btrim(message)) between 1 and 5000),
  created_at timestamptz not null default now()
);
create table if not exists public.integrations (
  id bigint generated by default as identity primary key,
  owner_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  provider text not null, configuration jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create table if not exists public.publication_jobs (
  id bigint generated by default as identity primary key,
  owner_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  status text not null default 'pending', payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create table if not exists public.administrative_records (
  id bigint generated by default as identity primary key,
  owner_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  record_type text not null, data jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.site_content add column if not exists status text not null default 'pending'
  check (status in ('pending', 'approved', 'hidden'));
alter table public.site_content add column if not exists visibility text not null default 'private'
  check (visibility in ('public', 'private'));
alter table public.site_content add column if not exists owner_id uuid default auth.uid()
  references auth.users(id) on delete set null;

alter table public.projects enable row level security;
alter table public.skills enable row level security;
alter table public.site_content enable row level security;
alter table public.contacts enable row level security;
alter table public.integrations enable row level security;
alter table public.publication_jobs enable row level security;
alter table public.administrative_records enable row level security;

-- Anonymous clients can only read records explicitly approved for publication.
create policy "public reads approved projects" on public.projects for select to anon, authenticated
  using ((status = 'approved' and visibility = 'public') or public.is_portfolio_owner());
create policy "public reads approved skills" on public.skills for select to anon, authenticated
  using ((status = 'approved' and visibility = 'public') or public.is_portfolio_owner());
create policy "public reads approved site content" on public.site_content for select to anon, authenticated
  using ((status = 'approved' and visibility = 'public') or public.is_portfolio_owner());

-- The public may submit only constrained contact fields; it can never read them.
create policy "public submits valid contact" on public.contacts for insert to anon, authenticated
  with check (
    char_length(btrim(name)) between 1 and 100
    and char_length(email) between 3 and 254
    and email ~* '^[^[:space:]@]+@[^[:space:]@]+\.[^[:space:]@]+$'
    and char_length(btrim(message)) between 1 and 5000
  );
create policy "owner manages contacts" on public.contacts for all to authenticated
  using (public.is_portfolio_owner()) with check (public.is_portfolio_owner());

-- Pending/hidden content and every administrative table are owner-only.
create policy "owner manages projects" on public.projects for all to authenticated
  using (public.is_portfolio_owner()) with check (public.is_portfolio_owner());
create policy "owner manages skills" on public.skills for all to authenticated
  using (public.is_portfolio_owner()) with check (public.is_portfolio_owner());
create policy "owner manages site content" on public.site_content for all to authenticated
  using (public.is_portfolio_owner()) with check (public.is_portfolio_owner());
create policy "owner manages integrations" on public.integrations for all to authenticated
  using (public.is_portfolio_owner() and owner_id = auth.uid())
  with check (public.is_portfolio_owner() and owner_id = auth.uid());
create policy "owner manages publication jobs" on public.publication_jobs for all to authenticated
  using (public.is_portfolio_owner() and owner_id = auth.uid())
  with check (public.is_portfolio_owner() and owner_id = auth.uid());
create policy "owner manages administrative records" on public.administrative_records for all to authenticated
  using (public.is_portfolio_owner() and owner_id = auth.uid())
  with check (public.is_portfolio_owner() and owner_id = auth.uid());

-- Existing curated seed data is the only content published by this migration.
update public.site_content set status = 'approved', visibility = 'public'
where page_key in ('home', 'projects', 'career');
