-- Public copy is managed in site_content; React components only render it.
update public.site_content set content = content || '{"seo":{"title":"About","description":"Professional profile, education and evidence-backed cybersecurity capabilities."},"principles_label":"Operating principles","principles_title":"Evidence, restraint, resilience.","education_label":"Education","capabilities_label":"Published capability record"}'::jsonb where page_key='about';
update public.site_content set content = content || '{"count_label":"outcomes","item_label":"OUTCOME"}'::jsonb where page_key='achievements';
update public.site_content set content = content || '{"count_label":"roles","item_label":"ROLE"}'::jsonb where page_key='experience';
update public.site_content set content = content || '{"count_label":"public cases","filters":{"search_label":"Search cases","search_placeholder":"Project, tool, domain…","capability_label":"Capability","all_capabilities":"All capabilities","evidence_label":"Evidence state","all_states":"All states","verified":"Verified","prepared":"Prepared","planned":"Planned","repository_label":"Public repository","record_label":"Project record","count_label":"cases","inspect_label":"Inspect case ↗","empty_message":"No case studies match those filters."}}'::jsonb where page_key='projects';
update public.site_content set content = content || '{"count_label":"active records","open_label":"Open source ↗"}'::jsonb where page_key='research';
update public.site_content set content = content || '{"status":"Evidence graph","explorer":{"loading_skills":"Loading skills…","api_unavailable":"Portfolio API is not configured.","skills_error":"Could not load skills","skills_empty":"No visible skills have been published yet.","loading_evidence":"Loading connected evidence…","evidence_error":"Could not load skill evidence","picker_label":"Select a skill","capability_label":"Capability evidence","verify_label":"Verify evidence ↗","unverified_label":"unverified","projects_label":"Projects","projects_empty":"No public projects connected yet.","credentials_label":"Credentials","credentials_empty":"No public credentials connected yet.","achievements_label":"Achievements","achievements_empty":"No public achievements connected yet."}}'::jsonb where page_key='skills';
update public.site_content set content = content || '{"channels_label":"Direct channels","linkedin_label":"LinkedIn ↗","privacy_note":"Messages are stored privately in Supabase and are not exposed through the public API.","form":{"name_label":"Name","email_label":"Email","message_label":"What security problem or opportunity should we discuss?","honeypot_label":"Website","submit_label":"Send message ↗","sending":"Sending securely…","success":"Message received. I’ll respond through your supplied email.","error":"Message could not be sent."}}'::jsonb where page_key='contact';
update public.site_content set content = content || '{"seo":{"title":"Cybersecurity Certifications","description":"Cybersecurity training and certification records with public verification links where available."},"count_singular":"public record","count_plural":"public records","verified_label":"Verified","verification_label":"Verification available","record_label":"Training record","issued_label":"Issued","expires_label":"Expires","verify_label":"Verify credential ↗","unavailable_message":"Certification records are temporarily unavailable.","empty_message":"No public certification records have been published."}'::jsonb where page_key='certifications';
update public.site_content set content = content || '{"menu_label":"Menu","navigation_label":"Primary navigation","header_cta":{"label":"View CV","href":"/cv"},"footer_link":{"label":"Contact","href":"/contact"}}'::jsonb where page_key='shell';
update public.site_content set content = content || '{"actions":{"projects":{"label":"View security projects","href":"/projects"},"cv":{"label":"Download CV","href":"/cv/download"},"contact":{"label":"Contact me ↗","href":"/contact"}},"labels":{"status_unavailable":"Portfolio status unavailable","recruiter_brief":"RECRUITER BRIEF","current":"CURRENT","profile":"PROFILE","base":"BASE","public_proof":"PUBLIC PROOF","security_cases":"SECURITY CASES","recruiter_summary":"Recruiter summary","unavailable":"Live portfolio records are temporarily unavailable.","case_label":"CASE","repository_label":"PUBLIC REPOSITORY","case_study_label":"CASE STUDY","projects_empty":"No featured projects have been published."},"sections":{"capabilities":{"eyebrow":"01 / Capability matrix","title":"Claims connected","emphasis":"to proof.","href":"/skills","link_label":"Inspect evidence →"},"projects":{"eyebrow":"02 / Featured operations","title":"Work that survives","emphasis":"inspection.","href":"/projects","link_label":"All case studies →"}}}'::jsonb where page_key='home';
update public.site_content set content = content || '{"labels":{"capabilities_empty":"No featured capabilities have been published.","verification_available":"verification available","training_record":"training record"},"sections":{"certifications":{"eyebrow":"03 / Certifications","title":"Structured learning","emphasis":"signals.","href":"/certifications","link_label":"View certifications →"},"recognition":{"eyebrow":"04 / Recognition","title":"Outcomes beyond","emphasis":"coursework.","href":"/achievements","link_label":"All achievements →"},"experience":{"eyebrow":"05 / Experience","title":"Delivery under","emphasis":"real constraints.","href":"/experience","link_label":"Full timeline →"},"research":{"eyebrow":"06 / Research","title":"Current line of","emphasis":"inquiry.","href":"/research","link_label":"Research record →"},"contact":{"eyebrow":"07 / CONTACT","title":"Need a security engineer","emphasis":"who values evidence?","href":"/contact","link_label":"Start a conversation","linkedin_label":"LinkedIn"}}}'::jsonb where page_key='home';

insert into public.site_content(page_key,content,visibility) values
('cv','{"eyebrow":"Curriculum vitae","download":{"label":"Download one-page PDF ↓","href":"/cv/download"},"projects_action":{"label":"View security projects ↗","href":"/projects"},"repository_label":"Public repository ↗","linkedin_label":"LinkedIn","github_label":"GitHub","sections":{"profile":"Profile","projects":"Selected security projects","experience":"Experience","education":"Education","skills":"Security capabilities","contact":"Contact"}}','public'),
('project_case','{"case_file":"CASE FILE","public_repository":"PUBLIC REPOSITORY","project_record":"PROJECT RECORD","view_repository":"View repository ↗","live_project":"Live project ↗","headline_outcome":"HEADLINE OUTCOME","evidence_label":"Evidence","media_label":"Media","skills_label":"Skills","view_source":"View source ↗","evidence_heading":"Evidence register","evidence_title":"Proof and","evidence_emphasis":"provenance.","project_media":"Project media","connected_capabilities":"Connected capabilities","sections":[{"field":"scope","fallback":"challenge","title":"Security problem and scope"},{"field":"contribution","title":"My contribution"},{"field":"architecture","title":"Architecture and decisions"},{"field":"process","fallback":"approach","title":"Tools and methodology"},{"field":"outcome","fallback":"description","title":"Results and validation"},{"field":"limitations","title":"Limitations and next steps"}]}','public'),
('open_graph','{"background":"#05090d","foreground":"#eaf4f2","border":"#1c2c34","accent":"#52f4d0","muted":"#82959b","eyebrow":"CAREEROS / PROFESSIONAL EVIDENCE","title":"Evidence over assumptions.","subtitle":"A recruiter-first, inspectable professional record","categories":"PROJECTS / RESEARCH / CERTIFICATIONS","status":"PUBLIC RECORD"}','public')
on conflict(page_key) do update set content=excluded.content,visibility='public',updated_at=now();
update public.site_content set content=content||'{"count_label":"published","read_label":"Read publication ↗"}'::jsonb where page_key='writing';
insert into public.site_content(page_key,content,visibility) values
('system_states','{"loading":{"eyebrow":"CareerOS / Loading","title":"Gathering the evidence.","message":"Loading the latest public work and capabilities…"},"error":{"eyebrow":"CareerOS / Recovery","title":"That route hit a temporary snag.","message":"The rest of the site is still available. Try this page again, or return to the public portfolio.","retry_label":"Try again","home_label":"Return home","home_href":"/"}}','public'),
('admin','{"eyebrow":"CareerOS / Owner session","title":"Content operations","intro":"Career records, display order, evidence, visibility and integration review are managed in Supabase Dashboard.","logout_label":"Sign out","cards":[{"title":"Career records","body":"Manage profile, projects, skills, certifications, achievements, experience and research in Table Editor."},{"title":"Evidence media","body":"Upload sanitized assets to the project-evidence bucket, then publish project_media records."},{"title":"Sync review","body":"Review external_items and approve canonical mapping before imported GitHub data becomes public."}]}','public'),
('admin_login','{"eyebrow":"CareerOS / Private","title":"Welcome back.","intro":"Sign in to access owner operations.","error_message":"Sign-in failed. Check your credentials and owner access.","email_label":"Email","password_label":"Password","submit_label":"Sign in securely →"}','public')
on conflict(page_key) do update set content=excluded.content,visibility='public',updated_at=now();
